name: build-and-test

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.12.0
      - name: Install dependencies
        run: yarn install
      - name: Run lint
        run: yarn lint
  deploy-preview:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v6
      - name: Build app
        uses: ./.github/actions/build/
        with:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      - name: Deploy preview
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./out --project-name=marutaku-blog --branch ${{ github.head_ref }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: ["deploy-preview"]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24.12.0
      - name: Install dependencies
        run: yarn install
      - name: Set current date (for cache key)
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Cache Playwright Browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ steps.date.outputs.date }}
          restore-keys: >-
            playwright-browsers-${{ runner.os }}-

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Show Playwright cache status
        run: >- 
          echo "Cache hit: ${{ steps.playwright-cache.outputs.cache-hit }}"
      - name: Run Playwright tests
        run: |
          PREVIEW_URL_PREFIX=$(echo '${{ github.head_ref }}' | sed 's/[^a-zA-Z0-9]/-/g' | cut -c-28)
          PLAYWRIGHT_BASE_URL=https://$PREVIEW_URL_PREFIX.next-cloudflare-blog.pages.dev yarn test:e2e
      - uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
